version: '2'
services:

  webapp:
    build: webapp/.
    ports:
      - '4200:80'
    links:
      - api
    depends_on:
      - api

  api:
    build: api/.
    ports:
      - '80:80'
    environment:
      DB_NAME: 'go'
      DB_USER: 'root'
      DB_PASSWORD: 123456
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    build: mysql/.
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'go'
      MYSQL_ROOT_PASSWORD: 123456