version: '2'
services:

  webapp:
    build: webapp/.
    ports:
      - '4200:80'
    links:
      - api
    depends_on:
      - api

  api:
    build: api/.
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    build: mysql/.
    environment:
      MYSQL_ROOT_PASSWORD: 123456